"$schema" = "https://starship.rs/config-schema.json"
command_timeout = 1500

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$custom \
\n$character"""


[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[custom.nodejs]
command = "asdf current nodejs | awk '{print $2}'"
description = "The currently installed version of NodeJS via asdf"
detect_files = ['package.json', '.node-version']
detect_folders = ["node_modules"]
detect_extensions = ["js", "ts"]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($output) ](fg:#769ff0 bg:#212736)]($style)'

[custom.golang]
command = "asdf current golang | awk '{print $2}'"
description = "The currently installed version of Golang via asdf"
detect_files = [
  'go.mod',
  'go.sum',
  'go.work',
  'glide.yaml',
  'Gopkg.yml',
  'Gopkg.lock',
  '.go-version',
]
detect_extensions = ["go"]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($output) ](fg:#769ff0 bg:#212736)]($style)'

[custom.rust]
command = "asdf current rust | awk '{print $2}'"
description = "The currently installed version of Rust via asdf"
detect_files = ['Cargo.toml']
detect_extensions = ["rs"]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($output) ](fg:#769ff0 bg:#212736)]($style)'

[custom.python]
command = "asdf current python | awk '{print $2}'"
description = "The currently installed version of Python via asdf"
detect_files = [
  '.python-version',
  'Pipfile',
  '__init__.py',
  'pyproject.toml',
  'requirements.txt',
  'setup.py',
  'tox.ini',
]
detect_extensions = ["py"]
symbol = "🐍"
style = "bg:#212736"
format = '[[ $symbol ($output) ](fg:#769ff0 bg:#212736)]($style)'
