# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
# in osx this should be in: ~/Library/Application Support/lazydocker/config.yml
gui:
  scrollHeight: 2
  returnImmediately: true
  language: en
  theme: # rose-pine theme
    activeBorderColor:
      - '#ebbcba' # Rose  – highlights the focused panel
      - bold
    inactiveBorderColor:
      - '#524f67' # Highlight‑High – subtle grey‑violet
    selectedLineBgColor:
      - '#26233a' # Overlay – row highlight
    optionsTextColor:
      - '#f6c177' # Gold – key‑hint menu & hotkeys
